import { Injectable } from '@angular/core';
import { hollandPregunta } from '../interfaces/holland-pregunta-intf';

@Injectable({
  providedIn: 'root'
})
export class HollandFirstService {

  constructor() { }

  preguntasHollandFirst: hollandPregunta[] = [
    {pregunta: 'Reparar artículos electrónicos', area : 'R'},
    {pregunta: 'Reparar automóviles', area : 'R'},
    {pregunta: 'Reparar artículos mecánicos', area : 'R'},
    {pregunta: 'Hacer artículos de madera', area : 'R'},
    {pregunta: 'Conducir camiones y tractores', area : 'R'},
    {pregunta: 'Utilizar herramientas mecánicas o de herrería', area : 'R'},
    {pregunta: 'Acondicionar un automóvil o bicicletas para carreras', area : 'R'},
    {pregunta: 'Tomar un curso taller', area : 'R'},
    {pregunta: 'Tomar un curso de dibujo mecánico', area : 'R'},
    {pregunta: 'Tomar un curso de labrado de madera', area : 'R'},
    {pregunta: 'Tomar un curso de mecánica automotriz', area : 'R'},
    {pregunta: 'Leer libros o revistas científicas', area : 'I'},
    {pregunta: 'Trabajar en un laboratorio', area : 'I'},
    {pregunta: 'Trabajar en un proyecto científico', area : 'I'},
    {pregunta: 'Construir modelos de cohetes', area : 'I'},
    {pregunta: 'Trabajar en un equipo de química', area : 'I'},
    {pregunta: 'Leer temas espaciales por mí mismo', area : 'I'},
    {pregunta: 'Resolver problemas de matemáticas o ajedrez', area : 'I'},
    {pregunta: 'Tomar un curso de química', area : 'I'},
    {pregunta: 'Tomar un curso de física', area : 'I'},
    {pregunta: 'Tomar un curso de geometría', area : 'I'},
    {pregunta: 'Tomar un curso de biología', area : 'I'},
    {pregunta: 'Bosquejar, dibujar o pintar', area : 'A'},
    {pregunta: 'Asistir a conciertos', area : 'A'},
    {pregunta: 'Diseñar muebles o edificios', area : 'A'},
    {pregunta: 'Tocar en una banda, conjunto u orquesta', area : 'A'},
    {pregunta: 'Tocar un instrumento musical', area : 'A'},
    {pregunta: 'Ir a recitales, conciertos o comedias musicales', area : 'A'},
    {pregunta: 'Leer novelas y temas de actualidad', area : 'A'},
    {pregunta: 'Hacer retratos o fotografía creativa', area : 'A'},
    {pregunta: 'Leer teatro', area : 'A'},
    {pregunta: 'Leer o escribir poesía', area : 'A'},
    {pregunta: 'Tomar un curso de arte', area : 'A'},
    {pregunta: 'Escribir cartas a los amigos', area : 'S'},
    {pregunta: 'Ir a la iglesía', area : 'S'},
    {pregunta: 'Pertenecer a grupos sociales', area : 'S'},
    {pregunta: 'Ayudar a otros en sus problemas personales', area : 'S'},
    {pregunta: 'Cuidar niños', area : 'S'},
    {pregunta: 'Asistir a fiestas', area : 'S'},
    {pregunta: 'Bailar', area : 'S'},
    {pregunta: 'Leer sobre psicología', area : 'S'},
    {pregunta: 'Asistir a reuniones y conferencias', area : 'S'},
    {pregunta: 'Asistir a eventos deportivos', area : 'S'},
    {pregunta: 'Hacer nuevos amigos', area : 'S'},
    {pregunta: 'Influir en los demás', area : 'E'},
    {pregunta: 'Vender', area : 'E'},
    {pregunta: 'Discutir sobre política', area : 'E'},
    {pregunta: 'Administrar mi propio servicio o negocio', area : 'E'},
    {pregunta: 'Asistir a conferencias', area : 'E'},
    {pregunta: 'Ofrecer pláticas', area : 'E'},
    {pregunta: 'Ser oficial de cualquier grupo', area : 'E'},
    {pregunta: 'Supervisar el trabajo de otros', area : 'E'},
    {pregunta: 'Conocer gente importante', area : 'E'},
    {pregunta: 'Dirigir un grupo para la consecución de un fin', area : 'E'},
    {pregunta: 'Participar en una campaña política', area : 'E'},
    {pregunta: 'Mantener en orden mi escritorio y habitación', area : 'C'},
    {pregunta: 'Mecanografiar documentos o cartas para mí o para otros', area : 'C'},
    {pregunta: 'Sumar, restar multiplicar números en negocios o administración', area : 'C'},
    {pregunta: 'Manejar máquinas de negocios de cualquier tipo', area : 'C'},
    {pregunta: 'Llevar un registro pormenorizado de gastos', area : 'C'},
    {pregunta: 'Tomar un curso de mecanografía', area : 'C'},
    {pregunta: 'Tomar un curso de comercio', area : 'C'},
    {pregunta: 'Tomar un curso de contabilidad', area : 'C'},
    {pregunta: 'Tomar un curso de matemáticas comerciales', area : 'C'},
    {pregunta: 'Archivar cartas, informes, registros, etc', area : 'C'},
    {pregunta: 'Escribir cartas de negocios', area : 'C'},
  ];

}
