import { Injectable } from '@angular/core';
import { hollandPregunta } from '../interfaces/holland-pregunta-intf';

@Injectable({
  providedIn: 'root'
})
export class HollandThirdService {

  constructor() { }

  preguntasHollandThird: hollandPregunta[] = [
    {pregunta: 'Mecánico', area : 'R'},
    {pregunta: 'Especialista en Piscicultura (crianza de especies marinas) o Agricultura', area : 'R'},
    {pregunta: 'Operador en una fábrica o industria', area : 'R'},
    {pregunta: 'Maestro gásfiter', area : 'R'},
    {pregunta: 'Operador de máquinas', area : 'R'},
    {pregunta: 'Investigador privado', area : 'R'},
    {pregunta: 'Inspector de construcciones', area : 'R'},
    {pregunta: 'Radiooperador', area : 'R'},
    {pregunta: 'Empleado en una gasolinera', area : 'R'},
    {pregunta: 'Diseñador de herramientas', area : 'R'},
    {pregunta: 'Fotograbador', area : 'R'},
    {pregunta: 'Electricista', area : 'R'},
    {pregunta: 'Ingeniero mecánico', area : 'R'},
    {pregunta: 'Meteorólogo', area : 'I'},
    {pregunta: 'Biólogo', area : 'I'},
    {pregunta: 'Astrónomo', area : 'I'},
    {pregunta: 'Ingeniero Civil', area : 'I'},
    {pregunta: 'Antropólogo', area : 'I'},
    {pregunta: 'Zoólogo', area : 'I'},
    {pregunta: 'Químico', area : 'I'},
    {pregunta: 'Investigador Científico', area : 'I'},
    {pregunta: 'Escritor de articulos científicos', area : 'I'},
    {pregunta: 'Geólogo', area : 'I'},
    {pregunta: 'Botánico', area : 'I'},
    {pregunta: 'Físico', area : 'I'},
    {pregunta: 'Poeta', area : 'A'},
    {pregunta: 'Director de conjunto u orquesta', area : 'A'},
    {pregunta: 'Músico', area : 'A'},
    {pregunta: 'Escritor', area : 'A'},
    {pregunta: 'Actor', area : 'A'},
    {pregunta: 'Dibujante', area : 'A'},
    {pregunta: 'Encargado de sonido', area : 'A'},
    {pregunta: 'Cantante', area : 'A'},
    {pregunta: 'Dramaturgo', area : 'A'},
    {pregunta: 'Director de cine o teatro', area : 'A'},
    {pregunta: 'Caricaturista', area : 'A'},
    {pregunta: 'Experto en obras de arte', area : 'A'},
    {pregunta: 'Compositor', area : 'A'},
    {pregunta: 'Misionero Religioso', area : 'S'},
    {pregunta: 'Profesor de Educación Física', area : 'S'},
    {pregunta: 'Orientador en asuntos de delincuencia juvenil', area : 'S'},
    {pregunta: 'Psicopedagogo', area : 'S'},
    {pregunta: 'Orientador Matrimonial', area : 'S'},
    {pregunta: 'Profesor de Educación Básica', area : 'S'},
    {pregunta: 'Director de organizaciones sociales', area : 'S'},
    {pregunta: 'Consejero', area : 'S'},
    {pregunta: 'Psicólogo', area : 'S'},
    {pregunta: 'Especialista en organizaciones sociales', area : 'S'},
    {pregunta: 'Trabajador en un hospital psiquiátrico', area : 'S'},
    {pregunta: 'Profesor de Educación Media', area : 'S'},
    {pregunta: 'Asesor de un municipio', area : 'S'},
    {pregunta: 'Ingeniero Comercial', area : 'E'},
    {pregunta: 'Especulador en bolsa', area : 'E'},
    {pregunta: 'Vendedor de acciones y títulos', area : 'E'},
    {pregunta: 'Agente de ventas', area : 'E'},
    {pregunta: 'Administrador de un hotel', area : 'E'},
    {pregunta: 'Representante de una empresa', area : 'E'},
    {pregunta: 'Ejecutivo de negocios', area : 'E'},
    {pregunta: 'Agente viajero', area : 'E'},
    {pregunta: 'Promotor', area : 'E'},
    {pregunta: 'Director de empresas', area : 'E'},
    {pregunta: 'Político', area : 'E'},
    {pregunta: 'Relacionador público', area : 'E'},
    {pregunta: 'Productor de televisión', area : 'E'},
    {pregunta: 'Contador', area : 'C'},
    {pregunta: 'Experto en control de calidad', area : 'C'},
    {pregunta: 'Director de tráfico', area : 'C'},
    {pregunta: 'Estadístico', area : 'C'},
    {pregunta: 'Secretario de un tribunal', area : 'C'},
    {pregunta: 'Tramitador aduanero', area : 'C'},
    {pregunta: 'Contralor de inventarios', area : 'C'},
    {pregunta: 'Analista de finanzas', area : 'C'},
    {pregunta: 'Evaluador', area : 'C'},
    {pregunta: 'Inspector de empresas', area : 'C'},
    {pregunta: 'Cajero', area : 'C'},
    {pregunta: 'Cobrador de un banco', area : 'C'},
    {pregunta: 'Especialista en impuestos', area : 'C'},
  ];
}
