// municipio.service.ts
import { Injectable } from '@angular/core';
import { HttpClient} from '@angular/common/http';
import { Municipio, MunicipioN } from '../interfaces/municipio-interface';
import { Municipioi } from '../interfaces/municipio-interface';
import { Observable } from 'rxjs';
import { environment } from '../../environments/environment';


@Injectable({
  providedIn: 'root'
})
export class MunicipioService {
  private apiUrl = `${environment.apiUrl}/municipio`;

  constructor(private http: HttpClient) { }
  getAll(): Observable<Municipioi[]> {
    return this.http.get<Municipioi[]>(`${this.apiUrl}`);
  }


  getById(id: number): Observable<Municipioi> {
    return this.http.get<Municipioi>(`${this.apiUrl}/${id}`);
  }
  municipios: Municipio[] = [
    new Municipio(1, 'Ixiamas', 1),
    new Municipio(2, 'San Buenaventura',1),
    new Municipio(2, 'Ayo Ayo', 2),
    new Municipio(3, 'Calamarca', 2),
    new Municipio(4, 'Collana', 2),
    new Municipio(5, 'Colquencha', 2),
    new Municipio(6, 'Patacamaya', 2),
    new Municipio(7, 'Sica Sica', 2),
    new Municipio(8, 'Umala', 2),
    new Municipio(9, 'Curva', 3),
    new Municipio(10, 'General Juan José Pérez (Charazani)', 3),
    new Municipio(11, 'Escoma', 4),
    new Municipio(12, 'Humanata', 4),
    new Municipio(13, 'Mocomoco', 4),
    new Municipio(14, 'Puerto Acosta', 4),
    new Municipio(15, 'Puerto Carabuco', 4),
    new Municipio(16, 'Alto Beni', 5),
    new Municipio(17, 'Caranavi', 5),
    new Municipio(18, 'Apolo', 6),
    new Municipio(19, 'Pelechuco', 6),
    new Municipio(20, 'Chacarilla', 7),
    new Municipio(21, 'Papel Pampa', 7),
    new Municipio(22, 'San Pedro de Curahuara', 7),
    new Municipio(23, 'Desaguadero', 8),
    new Municipio(24, 'Guaqui', 8),
    new Municipio(25, 'Jesús de Machaca', 8),
    new Municipio(26, 'San Andrés de Machaca', 8),
    new Municipio(27, 'Taraco', 8),
    new Municipio(28, 'Tiahuanaco', 8),
    new Municipio(29, 'Viacha', 8),
    new Municipio(30, 'Cajuata', 9),
    new Municipio(31, 'Colquiri', 9),
    new Municipio(32, 'Ichoca', 9),
    new Municipio(33, 'Inquisivi', 9),
    new Municipio(34, 'Licoma Pam', 9),
    new Municipio(35, 'Quime', 9),
    new Municipio(36, 'Catacora', 10),
    new Municipio(37, 'Santiago de Machaca', 10),
    new Municipio(38, 'Combaya', 11),
    new Municipio(39, 'Guanay', 11),
    new Municipio(40, 'Mapiri', 11),
    new Municipio(41, 'Quiabaya', 11),
    new Municipio(42, 'Sorata', 11),
    new Municipio(43, 'Tacacoma', 11),
    new Municipio(44, 'Tipuani', 11),
    new Municipio(45, 'Teoponte', 11),
    new Municipio(46, 'Cairoma', 12),
    new Municipio(47, 'Luribay', 12),
    new Municipio(48, 'Malla', 12),
    new Municipio(49, 'Sapahaqui', 12),
    new Municipio(50, 'Yaco', 12),
    new Municipio(51, 'Batallas', 13),
    new Municipio(52, 'Laja', 13),
    new Municipio(53, 'Puerto Pérez', 13),
    new Municipio(54, 'Pucarani', 13),
    new Municipio(55, 'Copacabana', 14),
    new Municipio(56, 'San Pedro de Tiquina', 14),
    new Municipio(57, 'Tito Yupanqui', 14),
    new Municipio(58, 'Aucapata', 15),
    new Municipio(59, 'Ayata', 15),
    new Municipio(60, 'Chuma', 15),
    new Municipio(61, 'Achocalla', 16),
    new Municipio(62, 'El Alto', 16),
    new Municipio(63, 'La Paz', 16),
    new Municipio(64, 'Mecapaca', 16),
    new Municipio(65, 'Palca', 16),
    new Municipio(66, 'Coroico', 17),
    new Municipio(67, 'Coripata', 17),
    new Municipio(68, 'Achacachi', 18),
    new Municipio(69, 'Ancoraimes', 18),
    new Municipio(70, 'Chua Cocani', 18),
    new Municipio(71, 'Huarina', 18),
    new Municipio(72, 'Huatajata', 18),
    new Municipio(73, 'Santiago de Huata', 18),
    new Municipio(74, 'Calacoto', 19),
    new Municipio(75, 'Caquiaviri', 19),
    new Municipio(76, 'Charaña', 19),
    new Municipio(77, 'Comanche', 19),
    new Municipio(78, 'Coro Coro', 19),
    new Municipio(79, 'Nazacara de Pacajes', 19),
    new Municipio(80, 'Santiago de Callapa', 19),
    new Municipio(81, 'Waldo Ballivián', 19),
    new Municipio(82, 'Chulumani', 20),
    new Municipio(83, 'Irupana', 20),
    new Municipio(84, 'La Asunta', 20),
    new Municipio(85, 'Palos Blancos', 20),
    new Municipio(86, 'Yanacachi', 20)
  ]

  municipiosN: MunicipioN[] = [
    new MunicipioN(1, 'Ixiamas', 'ABEL ITURRALDE'),
    new MunicipioN(2, 'San Buenaventura', 'ABEL ITURRALDE'),
    new MunicipioN(2, 'Ayo Ayo', 'AROMA'),
    new MunicipioN(3, 'Calamarca', 'AROMA'),
    new MunicipioN(4, 'Collana', 'AROMA'),
    new MunicipioN(5, 'Colquencha', 'AROMA'),
    new MunicipioN(6, 'Patacamaya', 'AROMA'),
    new MunicipioN(7, 'Sica Sica', 'AROMA'),
    new MunicipioN(8, 'Umala', 'AROMA'),
    new MunicipioN(9, 'Curva', 'BAUTISTA SAAVEDRA'),
    new MunicipioN(10, 'General Juan José Pérez (Charazani)', 'BAUTISTA SAAVEDRA'),
    new MunicipioN(11, 'Escoma', 'CAMACHO'),
    new MunicipioN(12, 'Humanata', 'CAMACHO'),
    new MunicipioN(13, 'Mocomoco', 'CAMACHO'),
    new MunicipioN(14, 'Puerto Acosta', 'CAMACHO'),
    new MunicipioN(15, 'Puerto Carabuco', 'CAMACHO'),
    new MunicipioN(16, 'Alto Beni', 'CARANAVI'),
    new MunicipioN(17, 'Caranavi', 'CARANAVI'),
    new MunicipioN(18, 'Apolo', 'FRANZ TAMAYO'),
    new MunicipioN(19, 'Pelechuco', 'FRANZ TAMAYO'),
    new MunicipioN(20, 'Chacarilla', 'GUALBERTO VILLAROEL'),
    new MunicipioN(21, 'Papel Pampa', 'GUALBERTO VILLAROEL'),
    new MunicipioN(22, 'San Pedro de Curahuara', 'GUALBERTO VILLAROEL'),
    new MunicipioN(23, 'Desaguadero', 'INGAVI'),
    new MunicipioN(24, 'Guaqui', 'INGAVI'),
    new MunicipioN(25, 'Jesús de Machaca', 'INGAVI'),
    new MunicipioN(26, 'San Andrés de Machaca', 'INGAVI'),
    new MunicipioN(27, 'Taraco', 'INGAVI'),
    new MunicipioN(28, 'Tiahuanaco', 'INGAVI'),
    new MunicipioN(29, 'Viacha', 'INGAVI'),
    new MunicipioN(30, 'Cajuata', 'INQUISIVO'),
    new MunicipioN(31, 'Colquiri', 'INQUISIVO'),
    new MunicipioN(32, 'Ichoca', 'INQUISIVO'),
    new MunicipioN(33, 'Inquisivi', 'INQUISIVO'),
    new MunicipioN(34, 'Licoma Pam', 'INQUISIVO'),
    new MunicipioN(35, 'Quime', 'INQUISIVO'),
    new MunicipioN(36, 'Catacora', 'JOSE MANUEL PANDO'),
    new MunicipioN(37, 'Santiago de Machaca', 'JOSE MANUEL PANDO'),
    new MunicipioN(38, 'Combaya', 'LARECAJA'),
    new MunicipioN(39, 'Guanay', 'LARECAJA'),
    new MunicipioN(40, 'Mapiri', 'LARECAJA'),
    new MunicipioN(41, 'Quiabaya', 'LARECAJA'),
    new MunicipioN(42, 'Sorata', 'LARECAJA'),
    new MunicipioN(43, 'Tacacoma', 'LARECAJA'),
    new MunicipioN(44, 'Tipuani', 'LARECAJA'),
    new MunicipioN(45, 'Teoponte', 'LARECAJA'),
    new MunicipioN(46, 'Cairoma', 'LOAYZA'),
    new MunicipioN(47, 'Luribay', 'LOAYZA'),
    new MunicipioN(48, 'Malla', 'LOAYZA'),
    new MunicipioN(49, 'Sapahaqui', 'LOAYZA'),
    new MunicipioN(50, 'Yaco', 'LOAYZA'),
    new MunicipioN(51, 'Batallas', 'LOS ANDES'),
    new MunicipioN(52, 'Laja', 'LOS ANDES'),
    new MunicipioN(53, 'Puerto Pérez', 'LOS ANDES'),
    new MunicipioN(54, 'Pucarani', 'LOS ANDES'),
    new MunicipioN(55, 'Copacabana', 'MANCO KAPAC'),
    new MunicipioN(56, 'San Pedro de Tiquina', 'MANCO KAPAC'),
    new MunicipioN(57, 'Tito Yupanqui', 'MANCO KAPAC'),
    new MunicipioN(58, 'Aucapata', 'MUÑECAS'),
    new MunicipioN(59, 'Ayata', 'MUÑECAS'),
    new MunicipioN(60, 'Chuma', 'MUÑECAS'),
    new MunicipioN(61, 'Achocalla', 'MURILLO'),
    new MunicipioN(62, 'El Alto', 'MURILLO'),
    new MunicipioN(63, 'La Paz', 'MURILLO'),
    new MunicipioN(64, 'Mecapaca', 'MURILLO'),
    new MunicipioN(65, 'Palca', 'MURILLO'),
    new MunicipioN(66, 'Coroico', 'NOR YUNGAS'),
    new MunicipioN(67, 'Coripata', 'NOR YUNGAS'),
    new MunicipioN(68, 'Achacachi', 'OMASUYOS'),
    new MunicipioN(69, 'Ancoraimes', 'OMASUYOS'),
    new MunicipioN(70, 'Chua Cocani', 'OMASUYOS'),
    new MunicipioN(71, 'Huarina', 'OMASUYOS'),
    new MunicipioN(72, 'Huatajata', 'OMASUYOS'),
    new MunicipioN(73, 'Santiago de Huata', 'OMASUYOS'),
    new MunicipioN(74, 'Calacoto', 'PACAJES'),
    new MunicipioN(75, 'Caquiaviri', 'PACAJES'),
    new MunicipioN(76, 'Charaña', 'PACAJES'),
    new MunicipioN(77, 'Comanche', 'PACAJES'),
    new MunicipioN(78, 'Coro Coro', 'PACAJES'),
    new MunicipioN(79, 'Nazacara de Pacajes', 'PACAJES'),
    new MunicipioN(80, 'Santiago de Callapa', 'PACAJES'),
    new MunicipioN(81, 'Waldo Ballivián', 'PACAJES'),
    new MunicipioN(82, 'Chulumani', 'SUDYUNGAS'),
    new MunicipioN(83, 'Irupana', 'SUDYUNGAS'),
    new MunicipioN(84, 'La Asunta', 'SUDYUNGAS'),
    new MunicipioN(85, 'Palos Blancos', 'SUDYUNGAS'),
    new MunicipioN(86, 'Yanacachi', 'SUDYUNGAS')
  ]
}
